//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artel.Telemetry.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diller
    {
        public int id { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Language { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public long TelegramId { get; set; }
        public Nullable<int> RegionID { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool Blocked { get; set; }
    }
}
