//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artel.Telemetry.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public int id { get; set; }
        public string Barcode { get; set; }
        public string LineNumber { get; set; }
        public string Camera_FronView { get; set; }
        public string Camera_BackRight { get; set; }
        public string Camera_BackLeft { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Comment { get; set; }
    }
}
